# [PyTorch - Learning the Basics](https://pytorch.org/tutorials/beginner/basics/intro.html)

In this first part, I'll go through the first section from the website on tensors.

## Tensors

Tensors are similar to arrays (lists) or matrices but are more specialized data structures. We'll use them to encode the inputs and outputs of a model, as well as the model's parameters.

The text notes that tensors are very similar to `numpy`'s `ndarrays`, except that tensors can run on GPUs. Tensors are also optimized for automatic differentiation, which will be covered in the [Autograd](https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html) section. Let's get started with some `import`ing.

In [1]:
import torch
import numpy as np

### Initializing a tensor

Tensors can be created directly from data, automatically inferring the data type.

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_data

tensor([[1, 2],
        [3, 4]])

We can also create tensors from `numpy` arrays.

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_np

tensor([[1, 2],
        [3, 4]])

We can even create tensors from other tensors. It'll retain the shape and datatype of the argument tensor, unless explicity overridden.

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random tensor: \n {x_rand}")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.7150, 0.5565],
        [0.3284, 0.4643]])


Let's see how we can create tensors with random or constant values. `shape` is a tuple of tensor dimensions, it determines the dimensionality of the output tensor.

In [7]:
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor}")

Random tensor: 
 tensor([[0.6250, 0.2424, 0.1608],
        [0.6173, 0.9929, 0.4864]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a tensor

A tensor's attributes describe its shape, datatype, and device on which it's stored.

In [8]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on tensors

[There are over 1,200 tensor operations](https://pytorch.org/docs/stable/torch.html):

- Arithmetic
- Linear algebra
- Matrix manipulation
  - Transposing
  - Indexing
  - Slicing
- Sampling
- More

The operations can be run on the CPU as well as an [Accelerator](https://pytorch.org/docs/stable/torch.html#accelerators), like CUDA, MPS (M1 Mac), MTIA, and XPU.

Tensors use the CPU by default. We can explicitly move the tensor to an accelerator using the `.to` method. Let's set a device.

In [10]:
# Set the tensor to use a device, if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

    print(f"Current accelerator: {torch.accelerator.current_accelerator()}")

Current accelerator: mps


Here are a few examples showing tensor manipulation in a `numpy`-like fashion.

In [ ]:
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

tensor[:, 1] = 0 # Set column index 1 to 0.
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


We can use `torch.cat` to concatenate a sequence of tensors along a given dimension. Another method that's slightly different is [`torch.stack`](https://pytorch.org/docs/stable/generated/torch.stack.html).

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

Below are a few examples of arithmetic operations on tensors.

In [13]:
# This computes the matrix multiplication between two tensors.
# y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product.
# z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

We can convert a single-element tnesor, if one, for example, was aggregated into one value, into a Python numberical value using `item()`.

In [14]:
agg = tensor.sum()
agg_item = agg.item()

print(agg_item, type(agg_item))

12.0 <class 'float'>


Operations that store the result into the operand are called **in-place** and are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t()`, will change `x`.

> **！Note**
>
> In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [15]:
print(f"{tensor} \n")

tensor.add_(5)

print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Bridge with `numpy`

Tensors on the CPU and `numpy` arrays can share their underlying memory locations, and changing one will also change the other.

Below is an example of a tensor to `numpy` array.

In [16]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the `numpy` array. This is different than I'm used to seeing, really interesting behavior.

In [17]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Here's an example of changing a `numpy` array to a tensor. Again, the changes in the `numpy` array reflect in the tensor.

In [18]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
